paths:
  uploads: public/uploads
  static: public
collections_config:
  homes:
    path: src/pages/homes
    icon: home
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  landing:
    path: src/pages/landing
    icon: padding
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_pages:
    path: src/pages
    icon: fit_page
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_data_post:
    path: src/data/post
    icon: compost
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
