paths:
  uploads: src/assets/images
  static: ''
collections_config:
  homes:
    path: src/pages/homes
    icon: home
    url: /homes/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  landing:
    path: src/pages/landing
    icon: padding
    url: /landing/[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: src/pages
    glob:
      - '*.astro'
      - '*.md'
    icon: fit_page
    url: /[full_slug]
    disable_url: false
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: src/data/post
    icon: newspaper
    url: /[slug]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false

_snippets:
  anchor:
    snippet: <a [[args]]>[[inner]]</a>
    params:
      args:
        parser: key_values
        options:
          models:
            - editor_key: href
          format:
            string_boundary:
              - '"'
            root_value_delimiter: '='
      inner:
        parser: content
        options:
          editor_key: text
  span:
    snippet: <span class=[[classes]]>[[inner]]</span>
    params:
      classes:
        parser: argument
        options:
          model:
            editor_key: classes
          format:
            string_boundary:
              - '"'
      inner:
        parser: content
        options:
          editor_key: text