paths:
  uploads: src/assets/images
  static: ''

collections_config:
  homes:
    path: src/pages/homes
    url: /homes/[slug]
    icon: home
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  landing:
    path: src/pages/landing
    url: /landing/[slug]
    icon: padding
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: src/pages
    url: /[full_slug]
    glob: 
      - '*.astro'
      - '*.md'
    icon: fit_page
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: src/data/post
    url: /[slug]
    icon: newspaper
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
